# name: Hexo Build and Deploy

# on:
#   push:
#     branches: [main]  # 你的主分支名称


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           submodules: recursive  # 拉取子模块
