name: Deploy Hexo to Github Pages
run-name: Deploy XhyBlog by @${{github.actor}}
on: 
  push:
    branch:
      - feat/workflows # 监听分支操作

jobs:
  build-and-deploy: # 任务 ： 构建部署
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version :
          - 18.19.1
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Nodejs # 配置node环境
      uses: actions/setup-node@v4
      with:
        node-version: '${{matrix.node-version}}'
    
    - name: Install Dependencies
      run : | 
        npm install -g hexo-cli
        npm install
    
    - name: Generate Static Files
      run: | 
        hexo clean 
        hexo generate
    
    - name: Configure SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SERVER_SSH_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: blogdist
        target: /home/ubuntu/dockers/nginx/html/